### PR TITLE
Replace binding to `setup_aerosol_optics`

### PR DESCRIPTION
**Pull request by lguez**
Replace binding between derived type `aerosol_optics_type` and
procedure `radiation_aerosol_optics_data::setup_aerosol_optics` by a
procedure pointer component.

The motivation is to allow the user of ECRad to use and read a NetCDF
file containing aerosol optical properties with a different structure
than `data/aerosol_ifs_rrtm_46R1_with_NI_AM.nc`.

The procedure `radiation_aerosol_optics::setup_aerosol_optics` defines
`radiation_aerosol_optics_data::setup_aerosol_optics` as the default
procedure pointed by `config%aerosol_optics%setup`. The user of ECRad
can choose another procedure before the call to
`radiation_aerosol_optics::setup_aerosol_optics`, for example in
`ecrad_driver` or in `radiation_setup::setup_radiation_scheme`, by
pointing `config%aerosol_optics%setup` or
`rad_config%aerosol_optics%setup` to a custom procedure.

### CODE REVIEW

**Comment by lguez** [comment]
Thank you for your answer.

> this feature is incomplete

Yes, you are right, some additional code change (one line actually) is needed, in `ecrad_driver` for example, to change the loader. If we want to use ECRad online, in a GCM, a line of code also has to be added in the GCM to  change the loader. The point is that this code change is made outside of ECRad. A user can integrate ECRad in a GCM and customize the loader without touching ECRad. Even `ecrad_driver` can be considered an outer part of ECRad. So for ECRad offline, you might expect the user to customize `ecrad_driver`.

>  "if" statements are used ...  I prefer a consistent style

OK, I see what you mean. Of course, "if" statements offer closed choices while the procedure pointer is an open choice. But OK.

> this adds code clutter

OK.

> It would be helpful to know what features you need that are not supported by the current aerosol optics format.

There is no missing feature, I think, in your NetCDF file. But I found it difficult to read and understand the first time I saw it. Here are the differences with our NetCDF file:

- Our file has groups instead of a flat structure.
- It has coordinates inside the groups (coordinate: monotonic one-dimensional variable with the same name as its dimension).
- The SW bands are in order, as befits a NetCDF coordinate.
- Spectral and relative humidity bounds are defined according to the CF convention.
- The unused variables, monochromatic single-scattering, asymmetry factor and lidar backscattering are not present.
- We do not characterize our aerosol types with a separate character code and a bin number. We do not use min and max radius.

[Here it is](https://mycore.core-cloud.net/index.php/s/dHZNtsEt1fFOL6L), if you want to see it. Of course, all these differences are just differences in form, we could adjust our creation process to mimic your NetCDF format. I still think it makes sense to leave input/ouput details open to the user if, as you say, you judge it does not clutter the code.

**Comment by rjhogan** [comment]
Thanks for the additional info!  Ultimately this is free software so you are welcome to modify your own version how you like for your own purposes, and as your changes are small you can still merge in any future upgrades of ecRad.  I see the benefit of the procedure pointer approach better now - but I think if I were to apply this then for consistencyI would use it for other things too (solver, cloud optics etc) which will need more thought, and I'd like to know there are other users who need it first.

I agree that the file could be more convention-conforming, and to some extent this could be easily achieved with my newer (simpler) 49r1 format since it works with wavenumber points not bands, but I can explain the current file structure:
 - Groups are annoying for reading the file in my opinion, and many platforms (including our Cray supercomputer, unfortunately) do not support NetCDF4/HDF5.
 - The SW bands are out of order because the RRTMG model (which I didn't write but is called by ecRad) has them out of order - if you reorder them then I'm pretty sure they'll be wrongly mapped to the available bands (i.e. I don't think the wavenumber bounds are checked)
 - The unused variables are actually used in the IFS when we do lidar and solar radiance assimilation
 - The aerosol codes and bin numbers are now needed even more (which is why they are more detailed in the newer format file) because I have added the facility for aerosol optical properties to be looked up by code/bin-num/optical-model, rather than just by index (positive/negative) which is error prone especially if someone changes the file. 
 - I'm a bit puzzled why you have so many missing values in your dataset.
 - 
The other reason for using ecRad's existing 49r1 format is that then other ecRad users would be able to try your optical properties. There is still scope to improve this format, and certainly scope to add things like standard_name.

**Comment by lguez** [comment]
> many platforms (including our Cray supercomputer, unfortunately) do not support NetCDF4/HDF5.

OK

> The SW bands are out of order because the RRTMG model (which I didn't write but is called by ecRad) has them out of order - if you reorder them then I'm pretty sure they'll be wrongly mapped to the available bands (i.e. I don't think the wavenumber bounds are checked)

You could cshift the variables just after reading them from the NetCDF file (this is what we do to use ECRad). Or maybe I miss something about the way the NetCDF file can be used.

>  The unused variables are actually used in the IFS when we do lidar and solar radiance assimilation

OK

> The aerosol codes and bin numbers are now needed even more (which is why they are more detailed in the newer format file) because I have added the facility for aerosol optical properties to be looked up by code/bin-num/optical-model, rather than just by index (positive/negative) which is error prone especially if someone changes the file.

OK

> I'm a bit puzzled why you have so many missing values in your dataset.

Yes, we only have LW properties for dust and seasalt.

> The other reason for using ecRad's existing 49r1 format is that then other ecRad users would be able to try your optical properties.

OK, good point.

Thanks.

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf-ifs/ecrad?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf-ifs/ecrad?pullRequest=9) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf-ifs/ecrad?pullRequest=9) it.</sub>

**Comment by lguez** [comment]
As we are making other changes on our master branch that are independent of this pull request, I have created a branch `pull_request_9` and it would make sense to correct this pull request: request to merge `lguez:pull_request_9` instead of `lguez:master`. I do not think I have the authorization to do this myself.

**Pull request closed without merging**
